  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/atsastry/confectionsbyarya:$COMMIT_SHA', '.']
    dir: 'frontend/'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/atsastry/confectionsbyarya:$COMMIT_SHA']
    dir: 'frontend/'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'github.com/atsastry/confectionsbyarya'
    - '--image'
    - 'gcr.io/$PROJECT_ID/github.com/atsastry/confectionsbyarya:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    dir: 'frontend/'
  images:
  - 'gcr.io/$PROJECT_ID/github.com/atsastry/confectionsbyarya:$COMMIT_SHA'
  options:
    logging: CLOUD_LOGGING_ONLY